// let emp = {
//     eid: 101,
//     ename: "RG",
//     gender: "Male"
// };
// console.log(emp);
// console.log(emp.eid);
// console.log(emp.ename);
// console.log(emp.gender);

let emps=[{"eid":1,"ename":"Zebulon","gender":"Male"},
{"eid":2,"ename":"Holmes","gender":"Male"},
{"eid":3,"ename":"Langston","gender":"Male"},
{"eid":4,"ename":"Bradney","gender":"Male"},
{"eid":5,"ename":"Neddie","gender":"Bigender"},
{"eid":6,"ename":"Orel","gender":"Female"},
{"eid":7,"ename":"Brnaby","gender":"Male"},
{"eid":8,"ename":"Winslow","gender":"Male"},
{"eid":9,"ename":"Mercy","gender":"Female"},
{"eid":10,"ename":"Gram","gender":"Male"},
{"eid":11,"ename":"Batsheva","gender":"Female"},
{"eid":12,"ename":"Wilhelmina","gender":"Female"},
{"eid":13,"ename":"Adorne","gender":"Bigender"},
{"eid":14,"ename":"Janetta","gender":"Genderqueer"},
{"eid":15,"ename":"Klemens","gender":"Male"},
{"eid":16,"ename":"Kaspar","gender":"Male"},
{"eid":17,"ename":"Charyl","gender":"Female"},
{"eid":18,"ename":"Marmaduke","gender":"Male"},
{"eid":19,"ename":"Elset","gender":"Female"},
{"eid":20,"ename":"Sigismondo","gender":"Male"},
{"eid":21,"ename":"Joseito","gender":"Male"},
{"eid":22,"ename":"Blaire","gender":"Female"},
{"eid":23,"ename":"Smith","gender":"Male"},
{"eid":24,"ename":"Farlie","gender":"Male"},
{"eid":25,"ename":"Hugh","gender":"Male"},
{"eid":26,"ename":"Miles","gender":"Male"},
{"eid":27,"ename":"Erika","gender":"Female"},
{"eid":28,"ename":"Davis","gender":"Male"},
{"eid":29,"ename":"Linda","gender":"Female"},
{"eid":30,"ename":"Teodoor","gender":"Male"},
{"eid":31,"ename":"Hastings","gender":"Male"},
{"eid":32,"ename":"Kylen","gender":"Female"},
{"eid":33,"ename":"Carmelia","gender":"Female"},
{"eid":34,"ename":"Alexandro","gender":"Male"},
{"eid":35,"ename":"Dot","gender":"Female"},
{"eid":36,"ename":"Arny","gender":"Male"},
{"eid":37,"ename":"Clea","gender":"Female"},
{"eid":38,"ename":"Ede","gender":"Female"},
{"eid":39,"ename":"Joella","gender":"Female"},
{"eid":40,"ename":"Cassandre","gender":"Female"},
{"eid":41,"ename":"Gypsy","gender":"Female"},
{"eid":42,"ename":"Joyan","gender":"Female"},
{"eid":43,"ename":"Mattias","gender":"Male"},
{"eid":44,"ename":"Britte","gender":"Female"},
{"eid":45,"ename":"Clevey","gender":"Male"},
{"eid":46,"ename":"Holt","gender":"Male"},
{"eid":47,"ename":"Hurleigh","gender":"Male"},
{"eid":48,"ename":"Dodi","gender":"Female"},
{"eid":49,"ename":"Corrianne","gender":"Polygender"},
{"eid":50,"ename":"Raynard","gender":"Male"},
{"eid":51,"ename":"Nickie","gender":"Male"},
{"eid":52,"ename":"Sisely","gender":"Female"},
{"eid":53,"ename":"Tony","gender":"Male"},
{"eid":54,"ename":"Dalton","gender":"Male"},
{"eid":55,"ename":"Avrit","gender":"Female"},
{"eid":56,"ename":"Reggis","gender":"Male"},
{"eid":57,"ename":"Irma","gender":"Female"},
{"eid":58,"ename":"Verile","gender":"Female"},
{"eid":59,"ename":"Haily","gender":"Female"},
{"eid":60,"ename":"Brandi","gender":"Female"},
{"eid":61,"ename":"Tove","gender":"Female"},
{"eid":62,"ename":"Patrica","gender":"Female"},
{"eid":63,"ename":"Sigismond","gender":"Male"},
{"eid":64,"ename":"Tris","gender":"Male"},
{"eid":65,"ename":"Harwilll","gender":"Male"},
{"eid":66,"ename":"Rona","gender":"Genderfluid"},
{"eid":67,"ename":"Rosalind","gender":"Female"},
{"eid":68,"ename":"Christos","gender":"Male"},
{"eid":69,"ename":"Sheppard","gender":"Male"},
{"eid":70,"ename":"Richmond","gender":"Male"},
{"eid":71,"ename":"Saudra","gender":"Female"},
{"eid":72,"ename":"Dulsea","gender":"Female"},
{"eid":73,"ename":"Bette","gender":"Female"},
{"eid":74,"ename":"Erinn","gender":"Agender"},
{"eid":75,"ename":"Arlene","gender":"Female"},
{"eid":76,"ename":"Vivian","gender":"Female"},
{"eid":77,"ename":"Dyanne","gender":"Bigender"},
{"eid":78,"ename":"Berni","gender":"Female"},
{"eid":79,"ename":"Sharai","gender":"Female"},
{"eid":80,"ename":"Wang","gender":"Male"},
{"eid":81,"ename":"Carmella","gender":"Female"},
{"eid":82,"ename":"Randie","gender":"Male"},
{"eid":83,"ename":"Gerianne","gender":"Female"},
{"eid":84,"ename":"Fara","gender":"Female"},
{"eid":85,"ename":"Kelby","gender":"Male"},
{"eid":86,"ename":"Boote","gender":"Male"},
{"eid":87,"ename":"Sinclair","gender":"Male"},
{"eid":88,"ename":"Wally","gender":"Non-binary"},
{"eid":89,"ename":"Lishe","gender":"Female"},
{"eid":90,"ename":"Jacobo","gender":"Male"},
{"eid":91,"ename":"Petra","gender":"Female"},
{"eid":92,"ename":"Kattie","gender":"Female"},
{"eid":93,"ename":"Didi","gender":"Female"},
{"eid":94,"ename":"Chaddy","gender":"Male"},
{"eid":95,"ename":"Felice","gender":"Male"},
{"eid":96,"ename":"Suzi","gender":"Female"},
{"eid":97,"ename":"Adolph","gender":"Male"},
{"eid":98,"ename":"Arturo","gender":"Male"},
{"eid":99,"ename":"Charley","gender":"Male"},
{"eid":100,"ename":"Cirillo","gender":"Male"}]

// for (let emp of emps) {
//     if (emp.gender==="Male")
//     console.log(emp);
// }

let malecount =0;
for (let emp of emps){
    if (emp.gender==="Male"){
    malecount++;
    }
}
console.log ("No of male employees: ", malecount) 